### ISSUE TITLE
undefined reference to `FvCB::FvCB_canopy_hourly

### ISSUE THREAD

**Issue by uhucrew** [zalf-lsa/monica#12]
Recently pulled build number 70 and cannot compile anymore. This Error occurs:

make
[ 20%] Built target libmonica
[ 21%] Linking CXX executable monica-run
libmonica.so: undefined reference to `FvCB::FvCB_canopy_hourly(FvCB::FvCB_canopy_hourly_in, FvCB::FvCB_canopy_hourly_params)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/monica-run.dir/build.make:616: monica-run] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/monica-run.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by bergm** [comment]
You have to update the util repository to the current version, then it should work again.

**Comment by uhucrew** [comment]
I updated the util repo earlier, git pull: "Already up-to-date."
Maybe the recent version isn't pushed?

**Comment by bergm** [comment]
Sorry, my mistake. In the project file there were two files missing, src\core\photosynthesis-FvCB.h and src\core\photosynthesis-FvCB.cpp. I added the project file with these two files to the monica repository and hope it should work now. The code is unused right now, unless you set an undocumented switch.
I hope it works now.

**Comment by uhucrew** [comment]
After adding new files in CMakeList.txt monica builds fine again.
Thank you very much!
